manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: badjeff
      revision: main
      import: app/west.yml
  self:
    path: config
